Manually start election
decidim-vocdoni/decidim-module-vocdoni pull request #61
Opened 2023-06-23 12:01 UTC by antopalidi

2023-06-28 09:02 UTC, andreslucena requested changes
I have the first round of feedback, can you check it out?

2023-06-28 09:05 UTC, andreslucena commented
@antopalidi if you agree with any of my suggestions please use the GitHub UI for accepting them (with the "Commit sugestion" or "Add suggestion to batch" buttons). This way will be easier and faster for you and the suggestions will be automatically marked as resolved conversations.

> One test fails on github, but as I understand it has no relation to my development.

They're related to #63, we probably missed them on that review. Can you fix them here though? So we have a green build before merging this one.

On another hand I think it's good that @carolromero also review this one so she can check the behavior. I'm not 100% if this should be marked by default and how it looks in the frontend before hitting the "Start election" button. Can you upload this branch to the staging server @antopalidi ?

2023-06-29 05:03 UTC, antopalidi commented
@andreslucena 
I have a question, do we need the `:manual_start_time_setting` configuration if it is used during the setup and creation of elections on the blockchain to set the start time.

First, I was set the start time after configuring the calendar when the manual start option was selected. But I was getting an error during setup election: "cannot add process with start block lower than or equal to the current height"

Now I think maybe set the start time during setup election to `Time.zone.now` without using this config.

2023-06-29 07:26 UTC, andreslucena commented
> "cannot add process with start block lower than or equal to the current height"

 The "blocks" in Vocdoni are how they actually keep track of time. I had this error when trying to set up an election with `start_time` in the past.

> Now I think maybe set the start time during setup election to Time.zone.now without using this config.

Try this out to see if it works multiple times. Mind that there's a delay between when we sent the operation and when they actually confirm that the operation was received and it's in the blockchain. You can check it out in the "Network" tab of your Web Development tools in your browser. So, I think that we may be bitten by this same error ("cannot add process with start block lower than or equal to the current height"). On another hand, we don't lose anything for trying it. 

For me, the 30 seconds delay is more than enough for waiting for the blockchain to actually confirm the operation.

2023-06-29 07:36 UTC, antopalidi commented
> For me, the 30 seconds delay is more than enough for waiting for the blockchain to actually confirm the operation.

@andreslucena 
I tried it. There was no error.  But if it will save from a possible error, it is better to set 30 seconds. You are right.
Then I will add a description to the README. I changed the rest.

2023-06-29 08:47 UTC, carolromero commented
@antopalidi thanks for all the work! 

here's my feedback after the review:

- [ ] In the pending steps shown on the dashboard, if you try to publish the election with "Fix it" before uploading the census, it shows you the message: "You are not authorized to perform this action":
![image](https://github.com/decidim-vocdoni/decidim-module-vocdoni/assets/23509895/146b647f-d45e-48f2-abd8-1872c369f605)

This makes sense, but then we should change the order of the validations, and have them displayed like this (I have also changed a little bit the validation text of the manual election):
![image](https://github.com/decidim-vocdoni/decidim-module-vocdoni/assets/23509895/736987fe-f4ad-4c76-af47-288f3a2fe031)


- [ ] I rewrote a little bit the message for the setup step:
![image](https://github.com/decidim-vocdoni/decidim-module-vocdoni/assets/23509895/df610e19-5607-4858-89f1-c5b5dbf89df4)
  Here's the copy:

  Election successfully configured!
  At this point you can still make changes if you see something misconfigured. [Make sure that you preview the election.](https://decidim-vocdoni.dev.pokecode.net/assemblies/general-assembly/f/3/elections/9)

  If you are comfortable with the current configuration, click on the "Setup election" button to send it to the Vocdoni Blockchain. 
  Then the election will be able to start.
  Please note that this action is irreversible, with no further modifications allowed.

- [ ] Regarding the frontend, if an election configured to start manually, let's hide the message: Voting begins on "Manual start"
![image](https://github.com/decidim-vocdoni/decidim-module-vocdoni/assets/23509895/e12607c9-d344-4aae-8aec-1fc260bffa60)

- [ ] Also in the frontend, I'm getting a server error when trying to view the election cards: https://decidim-vocdoni.dev.pokecode.net/assemblies/general-assembly/f/1/. I'd say that for now let's hide this section of the card if it is configured with manual start:
![image](https://github.com/decidim-vocdoni/decidim-module-vocdoni/assets/23509895/4126eea8-241f-489f-b895-323a83025a50)

2023-07-03 06:27 UTC, andreslucena commented on README.md
> +| VOCDONI_MINUTES_BEFORE_START | How many minutes should the setup be run before the election starts | `10`  |
There's an extra space here that:
```suggestion
| VOCDONI_MINUTES_BEFORE_START | How many minutes should the setup be run before the election starts | `10` |
```

This kind of changes make difficult to work with git tooling (for instance git blame)

2023-07-03 06:57 UTC, andreslucena commented on README.md
> +| VOCDONI_MANUAL_START_TIME_SETTING_IN_SECONDS | How many seconds there will be a delay to start the election with manual start after creating it on the blockchain | `30`  |
There's an extra space here: 
```suggestion
| VOCDONI_MANUAL_START_TIME_SETTING_IN_SECONDS | How many seconds there will be a delay to start the election with manual start after creating it on the blockchain | `30` |
```

2023-07-05 13:46 UTC, andreslucena submitted a review, later dismissed
LGTM! @microstudi do you want to give it an eye before merging?

2023-07-10 14:05 UTC, microstudi reviewed
I think we don't need the migration here as there's already an "auto_start" conf in the `election_type` field. We should change the backend to use only this field in order not to have repeated db data.

2023-07-17 11:00 UTC, microstudi approved these changes
All good now! Thanks everyone!

2023-07-17 11:00 UTC, merged