Honor "secrets until the end" check in frontend
decidim-vocdoni/decidim-module-vocdoni pull request #67
Opened 2023-07-19 07:11 UTC by antopalidi

fixes #59

2023-07-20 08:31 UTC, antopalidi commented
@andreslucena, this pr is ready for review

2023-07-24 10:43 UTC, carolromero commented on app/views/decidim/vocdoni/admin/election_calendar/edit.html.erb
>          </div>
@andreslucena @antopalidi I confirm it!

2023-07-24 11:26 UTC, antopalidi commented on app/forms/decidim/vocdoni/admin/election_calendar_form.rb
It's already been added there:

`secret_until_the_end: [true, false].sample`

2023-07-24 17:09 UTC, andreslucena requested changes
I have some more suggestions and I think this is ready 😄

2023-07-24 17:09 UTC, andreslucena commented on app/services/decidim/vocdoni/vocdoni_client.rb
> +        Decidim::Vocdoni.api_endpoint_url(api_endpoint_env)
Related to my other commend, we should take the env from the one already defined in Decidim::Vocdoni
```suggestion
        Decidim::Vocdoni.api_endpoint_url
```

2023-07-24 17:09 UTC, andreslucena commented on app/services/decidim/vocdoni/vocdoni_client.rb
> +      end
`:wallet` isn't used, and `:api_endpoint_env`, as I mentioned in other comments, can be inferred from `Decidim::Vocdoni` already.  Also I think it's better to just send the `:vocdoni_election_id` in the initializer. This is what I have in mind:

```suggestion
      attr_reader :vocdoni_election_id

      def initialize(vocdoni_election_id:)
        @vocdoni_election_id = vocdoni_election_id
      end

      def fetch_election
        fetch_from_api("/elections/#{vocdoni_election_id}")
      end
```

2023-07-24 17:09 UTC, andreslucena commented on app/controllers/decidim/vocdoni/elections_controller.rb
> +
Related to my other comments, I think we can simplify this a lot: 

```suggestion
      def vocdoni_client
        @vocdoni_client ||= VocdoniClient.new(vocdoni_election_id: election.vocdoni_election_id)
      end

      def election_metadata
        return nil unless !election.election_type["secret_until_the_end"] && election.ongoing?

        @election_metadata ||= vocdoni_client.fetch_election
      end
```

2023-07-25 07:36 UTC, antopalidi commented
@andreslucena all done

2023-07-25 08:06 UTC, andreslucena approved these changes
LGTM!! 
@microstudi can you take a look 🙏🏽 ?

2023-07-25 11:59 UTC, microstudi reviewed
Hi, the secret until the end feature looks great!

I have a concern, I see that the value "interruptible" comes from the module settings now and it is not configurable from the component.

Is there some reason for this change? maybe i am missing something.

2023-07-27 09:02 UTC, andreslucena commented
> Is there some reason for this change? maybe i am missing something.

As we've discussed in the Telegram chat, we've talked about not giving Admins this feature as it's something that they'd want to use almost always. 

If an installation needs to change this behaviour, they can do so by changing this in the initializer, so that works for that use case.

2023-07-27 09:34 UTC, merged