Upgrade 0.28
decidim-vocdoni/decidim-module-vocdoni pull request #78
Opened 2024-02-27 14:35 UTC by antopalidi

the review requires the previous PR to be merged #77

2024-05-21 11:24 UTC, microstudi requested changes
Very heavy work Anna, congratulations!
I left some minor comments just to clarify some things and some text changes.
After we sort that out, we are ready to merge!

2024-05-21 11:24 UTC, microstudi commented on app/views/decidim/vocdoni/admin/steps/_danger_zone.html.erb
> +<%# i18n-tasks-use t('decidim.vocdoni.admin.steps.danger_zone.messages.vote') %>
I see that we have lots of entries into the `i18n-tasks.yml` file. Maybe we can just add these there?

2024-05-21 11:24 UTC, microstudi commented on db/migrate/20240516163557_add_answers_count_to_decidim_vocdoni_questions.rb
> +
```suggestion
```
I guess this comes from a copy

2024-05-21 11:24 UTC, microstudi commented on package.json
> +    "@decidim/stylelint-config": "0.28.0",
Should this point to 0.28.1?

2024-05-21 11:24 UTC, microstudi commented on package.json
> +  "version": "2.0",
```suggestion
  "version": "2.0.0",
```

2024-05-21 11:24 UTC, microstudi commented on spec/system/decidim/admin/admin_creates_wallet_spec.rb
> +      end
This looks repeated from an example above, can we just add the "it" spec to the previous context "when prod environment"?

2024-05-21 11:24 UTC, microstudi commented on spec/system/decidim/admin/admin_creates_wallet_spec.rb
> +      end
Same here

2024-05-21 11:24 UTC, microstudi commented on app/packs/src/decidim/vocdoni/vocdoni_application.js
If this file is empty? shoudnt' we remove it along with all references to it?

2024-05-21 11:24 UTC, microstudi commented on app/cells/decidim/vocdoni/voting_step_navigation/show.erb
> +    <a></a>
this looks strange (I know that was there before), but do you know the reason why we put this empty link here?

2024-05-22 11:34 UTC, antopalidi commented on Rakefile
> +  FileUtils.cp("babel.config.json", "#{path}/babel.config.json")
I checked. It's still needed, otherwise there are errors

2024-05-22 14:57 UTC, merged